### ISSUE TITLE
Missing API-Functions

### ISSUE THREAD

**Issue by berti92** [HawtDogFlvrWtr/neatoscheduler_web#1]
Hello,

first things first... Thank you very much for your work regarding the neato!

I used your ESP-Image from your website. I changed the DNS to my local machine and reconnected the neato to my network. Now every request from the ESP goes to my local machine.
I see in the logs many error message, because of missing files or functions in the API.

Could you add the missinge API-Calls, so that I could use this repo local?

I could help if you want to.

Greetings, Berti.

**Comment by berti92** [comment]
As an example here an error message:

> [Sun Jan 19 16:24:24.235258 2020] [:error] [pid 9] [client 172.17.0.1:60740] script '/var/www/html/api/actionPull.php' not found or unable to stat
172.17.0.1 - - [19/Jan/2020:16:24:24 +0000] "GET /api/actionPull.php?serial=XXXX&battery=XXX&firmware=1.6&errorMsg=None HTTP/1.1" 404 407 "-" "ESP8266HTTPClient"

**Comment by nenonano** [comment]
I'm having the same issue

**Comment by nenonano** [comment]
found a solution, maybe THE solution.

rename api/callback.php to api/actionPull.php or, better (IMO), edit the .ino file in  https://github.com/HawtDogFlvrWtr/botvac-wifi and point the httpclient to api/callback.php

**Comment by berti92** [comment]
Can confirm that works, thank you! But sadly the json of the robot itself gets overwritten on every actionpull.

**Comment by nenonano** [comment]
indeed.
you can always modify the php file to save each file with a unique name (something like YYYYMMDDHHMMSS.json)

**Comment by berti92** [comment]
Yeah, thank you. But I'm not so good in PHP. I built a project in Node.js (to learn it) which is a telegram bot for the neato. I'll go further with this project and close this issue.
